name: Terraform Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-Workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: ls -la
      - name: terraform-version
        run: |
          terraform version
          echo "OK"
          
      - name: terraform-init
        run: |
          terraform init

      - name: terraform-validate
        run: |
          terraform validate

      - name: terraform-plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform plan -out tfplan

      - name: terraform-apply
        if: ${{ github.ref_name == "main" }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply "tfplan"
          echo "${GITHUB_REF_NAME}"
          echo "${{ github.ref_name }}"

      